version: '3'
services:
  hue:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcapitanio/hue:latest
    networks:
    - hadoop
    external_links:
    - hive
    - hadoop
    - zookeeper
    - postgres
    environment:
      PGPASSWORD: postgres
    ports:
    - 8000:8000
networks:
  hadoop:
    driver: bridge
volumes:
  hadoop_conf: null
  hive_conf: null
  hbase_conf: null
