version: "2"

services:

    hbase:
        image: mcapitanio/hbase:latest
        networks:
            - hadoop
        volumes:
            - hbase_logs:/opt/hbase/logs
            - hbase_conf:/opt/hbase/conf
        ports:
            - "8080:8080"
            - "8085:8085"
            - "9090:9090"
            - "9095:9095"
            - "60000:60000"
            - "60010:60010"
            - "60020:60020"
            - "60030:60030"

networks:
    hadoop:
        driver: bridge

volumes:
    hbase_logs:
    hbase_conf:
